# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/ovm/bridge.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'api/v1/ovm/bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/v1/ovm/bridge.proto\x12\x03ovm\"\r\n\x0bLoadRequest\"$\n\x0cLoadResponse\x12\x14\n\x05input\x18\x02 \x01(\tR\x05input\"\'\n\rSubmitRequest\x12\x16\n\x06output\x18\x01 \x01(\tR\x06output\"\x10\n\x0eSubmitResponse2l\n\x06\x42ridge\x12-\n\x04Load\x12\x10.ovm.LoadRequest\x1a\x11.ovm.LoadResponse\"\x00\x12\x33\n\x06Submit\x12\x12.ovm.SubmitRequest\x1a\x13.ovm.SubmitResponse\"\x00\x42Q\n\x07\x63om.ovmB\x0b\x42ridgeProtoP\x01Z\rgo/api/v1/ovm\xa2\x02\x03OXX\xaa\x02\x03Ovm\xca\x02\x03Ovm\xe2\x02\x0fOvm\\GPBMetadata\xea\x02\x03Ovmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.ovm.bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007com.ovmB\013BridgeProtoP\001Z\rgo/api/v1/ovm\242\002\003OXX\252\002\003Ovm\312\002\003Ovm\342\002\017Ovm\\GPBMetadata\352\002\003Ovm'
  _globals['_LOADREQUEST']._serialized_start=32
  _globals['_LOADREQUEST']._serialized_end=45
  _globals['_LOADRESPONSE']._serialized_start=47
  _globals['_LOADRESPONSE']._serialized_end=83
  _globals['_SUBMITREQUEST']._serialized_start=85
  _globals['_SUBMITREQUEST']._serialized_end=124
  _globals['_SUBMITRESPONSE']._serialized_start=126
  _globals['_SUBMITRESPONSE']._serialized_end=142
  _globals['_BRIDGE']._serialized_start=144
  _globals['_BRIDGE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
